[package]
name = "sacred_aurora"
version = "0.1.0"
edition = "2021"


[profile.dev.package."*"]
opt-level = 3




[dependencies]
bevy = "0.11.0"
bevy_rapier3d = {git = "https://github.com/dimforge/bevy_rapier", tag="v0.22.0", features = ["serde-serialize", "debug-render-3d"]}
bevy_editor_pls = {git = "https://github.com/jakobhellermann/bevy_editor_pls"}
bevy_fly_camera = {git = "https://github.com/sjael/bevy_fly_camera", branch="main"}
leafwing-input-manager = "0.10.0"
bevy_asset_loader = "0.17.0"
bevy_tweening = {git = "https://github.com/Sjael/bevy_tweening", branch="sjael"}
strum = "0.24.1"
strum_macros = "0.24.3"
lazy_static = "1.4.0"
# for geometric shapes as sprites
#bevy_prototype_lyon = "0.8.0" 


# Relatively stable crates down here
bitflags = "1.3"
derive_more = "0.99"
rand = "0.8.4"
serde = { version = "1.0", features = ["derive"] }
fixed = {version = "1.11", features = ["serde", "std", "serde-str"]}


# keep the following in sync with Bevy's dependencies for window icon
winit = { version = "0.28", default-features = false }
image = { version = "0.24", default-features = false }


[[bin]]
name = "local"
path = "src/local.rs"
