unstable_features = true
trailing_semicolon = false
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
max_width = 120
single_line_let_else_max_width = 120
attr_fn_like_width = 70
fn_call_width = 60